// exportFunctions.js
import Papa from "papaparse";
import { saveAs } from "file-saver";
import jsPDF from "jspdf";
import "jspdf-autotable";

/**
 * Export data to CSV
 */
export const exportToCSV = (
  headers,
  rows,
  filename = "report.csv",
  user = "Unknown"
) => {
  const timestamp = new Date().toLocaleString();
  const data = [
    ["Exported By:", user],
    ["Timestamp:", timestamp],
    [],
    headers,
    ...rows,
    [],
    ["Generated by TicketEase"],
  ];
  const csv = Papa.unparse(data);
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  saveAs(blob, filename);
};

/**
 * Export data to PDF
 */
export const exportToPDF = (
  headers,
  rows,
  title = "Report",
  filename = "report.pdf",
  user = "Unknown"
) => {
  const timestamp = new Date().toLocaleString();
  const doc = new jsPDF("landscape");

  // Add table
  doc.autoTable({
    head: [headers],
    body: rows,
    startY: 50,
    theme: "grid",
    headStyles: { fillColor: [54, 76, 110], textColor: [255, 255, 255] },
    bodyStyles: { fontSize: 10 },
  });

  // Add title and metadata
  doc.text(title, 20, 20);
  doc.text(`Exported By: ${user}`, 20, 30);
  doc.text(`Timestamp: ${timestamp}`, 20, 40);

  // Add footer (centered)
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.text(
    "Generated by TicketEase",
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 10,
    { align: "center" }
  );

  // Save PDF
  doc.save(filename);
};
